'use client';
import Head from 'next/head'
import { Inter } from '@next/font/google'
import React from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  return (
    <>
      <Head>
        <title>Lex-App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div class="d-flex flex-row mb-3" style={{ height: 100 + 'vh' }}>

        <div class="flex-grow-1 bg-dark text-center">
          <h2>database migrator v2</h2>
          <div className='my-5'>
            <p className='lead'>
              # start migration
              {/* button */}
              <br></br>
              <button className='btn btn-success' onClick={() => console.log('start migration')}>
                Start Migration
              </button>
            </p>
          </div>
        </div>
      </div>
    </>
  )
}
