'use client';
import Head from 'next/head'
import { Inter } from '@next/font/google'
import React from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  return (
    <>
      <Head>
        <title>Lex-App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div class="d-flex flex-row mb-3" style={{ height: 100 + 'vh' }}>

        <div class="flex-grow-1 bg-dark text-center">
          <h2>devBuggs's migrator</h2>
        </div>
      </div>
    </>
  )
}
